Consuming get
afaguilarr/workshop-api-testing-js pull request #9
Opened 2018-06-14 13:33 UTC by afaguilarr

2018-06-14 13:49 UTC, afaguilarr commented
Falta usar el método chai subset que se pide en el taller, todavía no está listo el PR

2018-06-14 20:37 UTC, svillegasz requested changes

2018-06-14 20:37 UTC, svillegasz commented on test/GithubApi.Repositories.test.js
> +    const query = {
El nombre de la variable es un poco confuso. No es un query, es la respuesta esperada del request

2018-06-14 20:37 UTC, svillegasz commented on test/GithubApi.Repositories.test.js
> +    return agent.get('https://api.github.com/users/aperdomob')
Recomendación. Intenta guardar urls/endpoints/resources en variables para mejorar la mantenibilidad

2018-06-14 20:37 UTC, svillegasz commented on test/GithubApi.Repositories.test.js
> +    const query = {
El nombre es un poco confuso

2018-06-14 20:37 UTC, svillegasz commented on test/GithubApi.Repositories.test.js
> +        const found = (response.body.items).find(repo => repo.name === 'jasmine-awesome-report');
No pareciera que los primeros parentesis sean necesarios

2018-06-14 20:37 UTC, svillegasz commented on test/GithubApi.Repositories.test.js
> +        const found = (response.body.items).find(repo => repo.name === 'jasmine-awesome-report');
Intenta reusar el nombre del query parameter para mejorar la consistencia y mantenibilidad

2018-06-14 20:37 UTC, svillegasz commented on test/GithubApi.Repositories.test.js
> +        expect(md5(file)).to.not.eql(unexpectedMd5);
Esta prueba no genera mucho valor, sería mas util si validamos con el hash esperado

2018-06-15 13:27 UTC, afaguilarr commented on test/GithubApi.Repositories.test.js
> +        expect(md5(file)).to.not.eql(unexpectedMd5);
Lo que pasa es que según le entendí a Salomón el md5 cambia  por lo que no existe un Md5 esperado :/

2018-06-15 13:49 UTC, svillegasz commented on test/GithubApi.Repositories.test.js
> +        expect(md5(file)).to.not.eql(unexpectedMd5);
Si siempre es el mismo archivo el hash va a ser siempre el mismo

2018-06-15 13:49 UTC, svillegasz approved these changes

2018-06-15 13:50 UTC, svillegasz commented
@afaguilarr Otro comentario 😅 . Cuando vuelvas a subir cambios y necesites mi revision, me puedes volver a asignar el PR

2018-06-15 14:08 UTC, merged